### ISSUE TITLE
Track liquidations of users in the lending protocol

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc-squid#103]
Required data-points:
- Repaid debt amount and token
- Seized collateral amount and token
- Cost of liquidation amount and token
- Timestamp
- Transaction id (extrinsic)

The USD amounts are not going to be stored in squid, so can be ignored.

Designs:

![image](https://user-images.githubusercontent.com/14966470/225547785-e97eadbb-83e3-48f8-b14e-b4c8e479c181.png)

Blocker for https://github.com/interlay/interbtc-ui/issues/869

**Comment by jtfirek** [comment]
Am I on the right track here @daniel-savu ?
This is the event I need to track:
```
        LiquidatedBorrow {
            liquidator: T::AccountId,
            borrower: T::AccountId,
            liquidation_currency_id: CurrencyId<T>,
            collateral_currency_id: CurrencyId<T>,
            repay_amount: BalanceOf<T>,
            collateral_underlying_amount: BalanceOf<T>,
        },
```
 repay_amount corresponds to: Repaid debt amount and token
 
collateral_underlying_amount corresponds to: Seized collateral amount and token

Do you have any thoughts on how I can get cost of liquidation and Transaction id

**Comment by daniel-savu** [comment]
> cost of liquidation

See this Discord discussion [here](https://discord.com/channels/745259537707040778/1079707148948361266/1082975872597901372) and [here](https://discord.com/channels/745259537707040778/1079707148948361266/1083339243746770984). TLDR: `collateral_underlying_amount - repay_amount`

> Transaction id

Good question, maybe there's a way to read that from the squid metadata of the event. You can check if the transaction id is used elsewhere in squid or the UI, or maybe ask Brendon.

**Comment by nud3l** [comment]
The event should have a filed "extrinsic" with an id. That is the transaction id.

**Comment by jtfirek** [comment]
@daniel-savu @nud3l  What currencies should I account for these values?
```
liquidation_currency_id: CurrencyId<T>,
collateral_currency_id: CurrencyId<T>,
```
 What token would you to see cost of liquidation represented as since it seems like I will be calculating this from collateral_underlying_amount and repay_amount?
