### ISSUE TITLE
Store all swaps

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc-squid#106]
We want to track historical swap data including:

- [ ] From asset
- [ ] To asset
- [ ] From amount
- [ ] To amount
- [ ] Fees paid
- [ ] Account
- [ ] Timestamp

**Comment by bvotteler** [comment]
> * Fees paid

@nud3l : This information is not available on the event. Should we create an issue in `interbtc` to add that info to the event?

Naturally, squid can query the chain, but we need to be very careful of the processing cost. If possible I'd like to avoid making squid processing slower due to additional lookups.

**Comment by bvotteler** [comment]
> * From asset
> * To asset
> * From amount
> * To amount

One more point to clarify: For multi-path swaps (e.g. KBTC -> KSM -> KINT), do we want to ignore the intermediate swaps and only track the first input / last output (KBTC in, KINT out, ignore KSM values)?

**Comment by gregdhill** [comment]
## `DexGeneral.AssetSwap`
- May include multiple hops in a single event
- The `amounts` vector includes the fee
- Swap fee and protocol fee customizable (protocol taken from swap)
- No events emitted for fee rate updates and not included in `PairCreated`

## `DexStable.CurrencyExchange`
- Fired per swap (includes pool and currency indices)
- Input amount includes fee
- Swap fee and admin fee customizable (admin taken from swap)
- `NewSwapFee` and `NewAdminFee` update fee rates, not included in `CreatePool`

## `DexStable.CurrencyExchangeUnderlying`

- Same as above but currency index over two pools

**Comment by bvotteler** [comment]
PR: #110 

Sample query and result shown in [this comment](https://github.com/interlay/interbtc-squid/pull/114#issuecomment-1516392143)
