### ISSUE TITLE
Store LP per account

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc-squid#111]
We want to know how many users and how often they LP into pools. We want to track the deposits and withdrawals from pools for this.

We'd want the following data:

- `amounts` (as in `cumulativeDexTradingVolumes`) consisting of `amount`, `amountHuman`, and `token`
- `tillTimestamp`
- `type` of either `deposit` or `withdrawn`
- `block`
- `accountId`

**Comment by bvotteler** [comment]
PR #115 is up for review

See a sample query and results in [this comment](https://github.com/interlay/interbtc-squid/pull/115#issuecomment-1517888088).
