### ISSUE TITLE
Add an additional `amountHuman` to currency fields that uses the "regular" representation

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc-squid#37]
When adding grafana dashboards, it's quite difficult to deal with scaling the currency amounts stored in the satoshi/planck representations (0 decimals).

Key issues:
- Each query needs to have a manual transformation that scales the currency. However, since currencies have different decimals (Dot 10, KSM 12, USDT 6, iBTC 8, ...), queries need to be broken up to transform values correctly.
- For foreign assets, the problem is even more severe. For example, foreign asset `2` is LKSM on Kintsugi and USDT on Interlay. This requires different handling and more logic that is not easily representable in grafana.

Instead of handling the decimal representation in the representation layer, squid should all a `amountHuman` field that returns the typical representation, e.g., in BTC, DOT, KSM, iBTC, ...

**Comment by nud3l** [comment]
Thinking about this, maybe we want to stick to a naming scheme appending `Human` to the original value. So, e.g., on the issue model, we'd have `griefingCollateral` and `griefingCollateralHuman` as well as `backingPayment` and `backingPaymentHuman`. Otherwise, it might be difficult to track what `amountHuman` would refer to.

On the oracle specifically, I think it worthwhile to add `updateValueHuman` but this one is a bit involved. Maybe we can reuse some function from the lib here: https://github.com/interlay/interbtc-api/blob/master/src/parachain/oracle.ts#L112

@bvotteler @peterslany what do you guys think?

**Comment by peterslany** [comment]
> Thinking about this, maybe we want to stick to a naming scheme appending `Human` to the original value. 

I agree, it makes sense to do it in this explicit way :+1:
