### ISSUE TITLE
Workflow for updating the SQL schema is out of order.

### ISSUE THREAD

**Issue by jtfirek** [interlay/interbtc-squid#58]
Step 4 of running gen:code needs to done before running db:create-migration. And then `yarn build` after `gen:code` but before `db-create-migration`. 

The db:create-migration needs the compiled changes to detect changes that affect these files.

**Workflow - updating the SQL schema**
The GraphQL entities are defined in schema.graphql. When the schema is changed:

1. Ensure your DB is up to date (e.g. you recently ran yarn db:migrate)
2. Run yarn db:create-migration, and enter a name for the migration. This will auto-generate it.
3. Run yarn db:migrate to apply your new migration. (Or yarn db:reset if you wish to restart processing on the newly migrated DB, which is often a new idea - db:reset automatically applies runs migrate as well.)
4. Run yarn gen:code to regenerate Typescript types for the GraphQL entities.
5. You can now develop the mappings against the new entities. Run yarn build as usual to proceed.

**Comment by bvotteler** [comment]
Related to issue #43

**Comment by bvotteler** [comment]
Edited description to point out the order should be (1) `yarn db:migrate` -> (2, was 4) `yarn gen:code` -> (3, new) `yarn build` -> (4, was 3) `yarn db:create-migration` -> ...
