### ISSUE TITLE
Remove the Distributable Folder

### ISSUE THREAD

**Issue by jtfirek** [interlay/interbtc-squid#63]
I think this code is old and we do don't use it anymore. I deleted this folder and ran the graphql server with no issues.

**Comment by bvotteler** [comment]
I'm not entirely sure if the distributables folder isn't used somewhere in the deployment scripts. So please do check if there are any traces in guthub actions, or docker files in the project that look as if they rely on using those files.
Similar for deployment scripts - we should check in with Nikolai if there are any other scripts that we may have missed that might use the distributable folder before we remove it.

**Comment by bvotteler** [comment]
After checking this a bit more thoroughly, I think we can safely go ahead. I found no signs of the distributables being used in our org's repositories. And the package hasn't been published to npm, either. So there are no potential dependents on that front, either.
