### ISSUE TITLE
Transfer query does not support LendToken, LpToken, or StableLpToken

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc-squid#89]
**Context**
For the testnet competition, we need to filter transfers made by users to see if they were trying to cheat.

**Problem**

The current query only supports `NativeToken` and `ForeignAsset`. The new token types `LendToken`, `LpToken`, and `StbleLpToken` are not yet supported. Hence, if users send these tokens to their own accounts, we cannot detect it.

**Steps to reproduce**

1. Go to https://api-dev-kintsugi.interlay.io/graphql/graphql
2. Enter query
```graphql
query MyQuery {
  transfers(limit: 10) {
    amount
    from
    to
    timestamp
    token {
      ... on NativeToken {
        token
      }
      ... on ForeignAsset {
        asset
      }
    }
  }
}
```
3. See that adding other token types is not supported

**Comment by bvotteler** [comment]
This has been fixed with the redeployment of squid recently.
ie. The types were there, but our deployment used outdated images at the time.

Right now, I am able to query for all new currency types:
```
query MyQuery {
  transfers(limit: 10) {
    amount
    from
    to
    timestamp
    token {
      ... on NativeToken {
        token
      }
      ... on ForeignAsset {
        asset
      }
      ... on LendToken {
        __typename
        lendTokenId
      }
      ... on StableLpToken {
        __typename
        poolId
      }
      ... on LpToken {
        __typename
        token0 {
          ... on NativeToken {
            __typename
            token
          }
          ... on ForeignAsset {
            __typename
            asset
          }
          ... on StableLpToken {
            __typename
            poolId
          }
        }
        token1 {
          ... on NativeToken {
            __typename
            token
          }
          ... on ForeignAsset {
            __typename
            asset
          }
          ... on StableLpToken {
            __typename
            poolId
          }
        }
      }
    }
  }
}
```

**Comment by nud3l** [comment]
Can confirm it works now. Thanks for updating and closing the issue!
